mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
    path('logout/', views.logout_member, name='logout'),
	path('login/', views.login_member, name='login'),
	path('register/', views.register, name='register'),
    path('stocks/', include('stock_data.urls')),
    path('admin/', admin.site.urls),
]

mysite/stock_data/urls.py
from django.urls import path

from . import views

app_name = 'stock_data'
urlpatterns = [
	#path('data_fetching/', views.data_fetching, name='data_fetching'),
	#path('result/', views.result, name='result'),
    path('', views.index, name='index'),
]

mysite/stock_data/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Stocks(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	stock_list = models.CharField(max_length=200)

mysite/mysite/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# class LoginForm(forms.Form):
# 	username = forms.CharField(label='Username', max_length=100)
# 	password = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100)

# class RegisterForm(forms.Form):
# 	first_name = forms.CharField(label='First name', max_length=100)
# 	last_name = forms.CharField(label='Last name', max_length=100)
# 	username = forms.CharField(label='Username', max_length=100)
# 	password = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100)
# 	email = forms.CharField(widget=forms.EmailInput, label='Email', max_length=100)

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
    #     widgets = {
    #     'password': forms.PasswordInput(),
    # }

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        #fields = ['first_name', 'last_name', 'username', 'email', 'password']
    #     widgets = {
    #     'password': forms.PasswordInput(),
    # }

mysite/stock_data/forms.py
from django import forms

class NameForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)

mysite/mysite/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from stock_data.models import Stocks

from .forms import LoginForm, RegisterForm

from bs4 import BeautifulSoup
import requests
import json

def home(request):
	template = loader.get_template('stock_data/home.html')
	context = {}
	return HttpResponse(template.render(context, request))

def login_member(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		form = LoginForm(data=request.POST)
		# print("form: " + str(form))
		# print("request.POST: " + str(request.POST))
		#print(form.error)
		#print(form.is_bound)
		if form.is_valid():
			# process the data in form.cleaned_data as required
			# ...
			user = authenticate(request, username=username, password=password)
			print("in VALID")
			if user is not None:
				print("init")
				login(request, user)
				# A backend authenticated the credentials
			else:
				print("WOW")
				# No backend authenticated the credentials
			# redirect to a new URL:
			return HttpResponseRedirect('/stocks/')

	# if a GET (or any other method) we'll create a blank form
	else:
		form = LoginForm()
	return render(request, 'stock_data/login.html', {'form': form})

def register(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		# print("form: " + str(form))
		# print("request.POST: " + str(request.POST))
		if form.is_valid():
			# process the data in form.cleaned_data as required
			# ...
			form.save()

			# redirect to a new URL:
			return HttpResponseRedirect('/login/')

	# if a GET (or any other method) we'll create a blank form
	else:
		form = RegisterForm()
	return render(request, 'stock_data/register.html', {'form': form})

def logout_member(request):
	logout(request)
	return render(request, 'stock_data/logout.html')



#render(request, 'mysite/home.html')

mysite/stock_data/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Stocks

from iexfinance import Stock as stock_pull
import requests
import json
import time

@login_required(login_url='/login/')
def index(request):
	# Check to see if the logged in user has any stocks they are following, via the Stocks model
	current_user = User.objects.get(username=request.user)
	try:
		model_stocks_list = Stocks.objects.get(user=current_user)
	# If user does not have any stocks, make a new instance for them in the Stocks model, but make it blank
	except Stocks.DoesNotExist:
		context = {}
		s = Stocks(user=current_user, stock_list = '')
		s.save()
		return render(request, 'stock_data/index.html', context)

	# If user had a stock watch list, convert that data into a list structure
	stocks_list = model_stocks_list.stock_list.split(', ')

	if request.method == 'POST':
		# If the user submits the form with a company name, we should add this to the stocks_list variable
		if stocks_list != ['']:
			stocks_list.append(request.POST['stock_symbol'])
		else:
			stocks_list = [request.POST['stock_symbol']]

		# Now, convert the list of stocks into a string again and save it into the model
		model_stocks_list.stock_list = ', '.join(stocks_list)
		model_stocks_list.save()

	# Using the IEXTrading module, pull the latest stock data from their API for each stock the user is following
	# Store this data in a context variable for the html generation
	ohlc_data_dict = {}
	for stock in stocks_list:
		try:
			get_stock_ohlc = stock_pull(stock).get_ohlc()
			ohlc_data_dict[stock] = [get_stock_ohlc["open"]["price"], get_stock_ohlc["high"], get_stock_ohlc["low"], get_stock_ohlc["close"]["price"]]
		except ValueError:
			pass
	context = {'ohlc_data': ohlc_data_dict}
	return render(request, 'stock_data/index.html', context)

mysite/mysite/templates/mysite/home.html
test

mysite/stock_data/templates/stock_data/base.html
{% load static %}

<head>
	<title>My Stockboard</title>
 	<link rel="stylesheet" type="text/css" href="{% static 'stock_data/styles.css' %}"/>
 	<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
</head>

<h1><a href={% url 'home' %}>My Stockboard</a></h1>
{% if user.is_authenticated %}
	<p>You are logged in as: {{ request.user }}</p>
{% endif %}
<hr>
<ul>
	<li><a href={% url 'home' %}>Home</a></li>
	{% if user.is_authenticated %}
		<li><a href={% url 'stock_data:index' %}>Stocks portfolio</a></li>
		<li><a href={% url 'logout' %}>Logout</a></li>	
	{% else %}
		<li><a href={% url 'register' %}>Register</a> or <a href={% url 'login' %}>Login</a></li>	
	{% endif %}
</ul>
<hr>

{% block content %}
{% endblock %}

mysite/stock_data/templates/stock_data/home.html
{% extends "./base.html" %}

{% block content %}
<body>
  <div class="main">

    <p>My Stockboard (MS) is a platform where users can follow stocks they have invested or are interested in. 
    	{% if not user.is_authenticated %}
    		Please <a href={% url 'register' %}>register</a> or <a href={% url 'login' %}>login</a> to get started!</p>
    	{% endif %}
    <h2>Time until U.S. markets open: </h2>
    <h2 id="demo"></h2>
  </div>
</body>
{% endblock %}

mysite/stock_data/templates/stock_data/index.html
{% extends "./base.html" %}

{% block content %}
	<form action="{% url 'stock_data:index' %}" method="post">
		{% csrf_token %}
  		<label for="POST-stock-symbol">Which stock do you want information on?</label>
  		<input id="POST-stock-symbol" type="text" name="stock_symbol">
  		<input type="submit" value="Submit">
	</form>

	<h2>Your stocks:</h2>
  {% if ohlc_data %}
    {% for stock_symbol, ohlc in ohlc_data.items %}
      <h3>{{ stock_symbol }}'s OHLC Data:</h3>
      <ul>
          <li>Open: {{ ohlc.0 }} </li>
          <li>High: {{ ohlc.1 }}</li>
          <li>Low: {{ ohlc.2 }}</li>
          <li>Close: {{ ohlc.3 }}</li>     
      </ul>
      <hr>
    {% endfor %}
  {% else %}
    <p>There is currently no stock data available for </p>
  {% endif %}
{% endblock %}

mysite/stock_data/templates/stock_data/login.html
{% extends "./base.html" %}

{% block content %}
<form action={% url 'login' %} method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="OK">
</form>
{% endblock %}

mysite/stock_data/templates/stock_data/logout.html
{% extends "./base.html" %}

{% block content %}
You have been succesfully logged out!
{% endblock %}

mysite/stock_data/templates/stock_data/register.html
{% extends "./base.html" %}

{% block content %}
<form action={% url 'register' %} method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="OK">
</form>
{% endblock %}

mysite/stock_data/templates/stock_data/stock_info.html
{% if ohlc_data %}
	Latest data for: {{ stock_symbol }}
    <ul>
    {% for data_point_key, data_point_value in ohlc_data.items %}
        <li>{{ data_point_key }}: {{ data_point_value }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>There is currently no stock data available for </p>
{% endif %}